### ISSUE TITLE
False hits by EPISODES_LIST_REGEX

### ISSUE THREAD

**Issue by pavelruzicka** [luk27official/ivysilani-mpd-extractor#2]
Hi,

I have run into an issue with the extractor. The `EPISODES_LIST_REGEX` seems to be misconfigured – I have passed in the URL https://www.ceskatelevize.cz/porady/14757154647-karel-kryl-v-dansku/, which links to a movie, but the regex `r"https://www.ceskatelevize.cz/[^/]*/[^/]*/$"` incorrently found a match. I am not sure whether there is a bulletproof way to tell whether an URL links to a movie or a show based solely on the URL.

I have obviously found my way around this issue so please do not feel urged to fix it asap, just letting you know.

**Comment by luk27official** [comment]
Hi,
thanks for the report. Instead of the regex, I have added a different check - the extractor instead looks for "Přehrát * díl" (* stands for "nejnovější", "první" etc. I think it should work for now.

Let me know if you encounter any unexpected behavior.

**Comment by pavelruzicka** [comment]
I have not, it works like a charm. Thanks!
