### ISSUE TITLE
"Přehrát" button not found on time-limited resources

### ISSUE THREAD

**Issue by pavelruzicka** [luk27official/ivysilani-mpd-extractor#3]
Hi,

as the issue name suggests, the Přehrát button which the extractor relies on can not be found on URLs linking to resources which are time limited. For example, https://www.ceskatelevize.cz/porady/14757154647-karel-kryl-v-dansku/ expires on December 1st which makes the play button display a custom text ("_Přehrát (dostupné do 1. 12. 21:30)_"). I suggest only checking whether the button innerHTML starts with "Přehrát"?

I have obviously found my way around this issue so please do not feel urged to fix it asap, just letting you know.

EDIT: Sorry, I thought the XPath selector was checking for innerHTML but it relies on the ARIA label. That seems to be missing altogether on the time-expiring play button.

**Comment by luk27official** [comment]
Hi,
thanks for the report. Changed:
https://github.com/luk27official/ivysilani-mpd-extractor/blob/a345ac3b552136e9dc1bee5d7b40c7ec8fa80e5c/extract.py#L19-L20
Let me know if you encounter any unexpected behavior.

**Comment by pavelruzicka** [comment]
Works as expected. Thanks for the lightning fix!

**Comment by pavelruzicka** [comment]
Thanks for the lightning response.

The `SERIES_RUN_XPATH` selector seems to be unable to find the play button. I encounter this issue on https://www.ceskatelevize.cz/porady/1093417350-manez-bolka-polivky/, for example.

The traceback ends with `selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[starts-with(normalize-space(text()), "Přehrát")]"`.

**Comment by luk27official** [comment]
Indeed, I have tried it myself, and it had worked just for the first episode. For the [second episode](https://www.ceskatelevize.cz/porady/1093417350-manez-bolka-polivky/30023633284/), the app crashed - this happened because of licence issues - the second episode is not available ("Nemáme licenci pro přehrání na internetu").

I have added a check that should handle this in 934deb6.
